# Generated by Django 4.2.6 on 2023-11-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.insumo', verbose_name='Insumo'),
        ),
    ]
