# Generated by Django 4.2.6 on 2023-11-06 18:24

import apps.ventas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_alter_detallecompra_cantidad_and_more'),
        ('empresa', '0005_alter_stockinsumo_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(default=apps.ventas.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=155, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('correo_electronico', models.EmailField(max_length=255, verbose_name='Correo Electrónico')),
                ('celular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de celular')),
                ('nit', models.CharField(blank=True, max_length=55, null=True, verbose_name='NIT')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón social')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.CharField(default=apps.ventas.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nit', models.CharField(blank=True, max_length=55, null=True, verbose_name='NIT')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón social')),
                ('tipo', models.CharField(choices=[('Servicio', 'Servicio'), ('Compra', 'Compra')], max_length=125, verbose_name='Tipo')),
                ('detalle', models.TextField(blank=True, max_length=800, null=True, verbose_name='Detalle')),
                ('total', models.FloatField(verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id_recibo', models.CharField(default=apps.ventas.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('Servicio', 'Servicio'), ('Compra', 'Compra')], max_length=125, verbose_name='Tipo')),
                ('detalle', models.TextField(blank=True, max_length=800, null=True, verbose_name='Detalle')),
                ('total', models.FloatField(verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'recibo',
            },
        ),
        migrations.CreateModel(
            name='ResultadoAnalisis',
            fields=[
                ('id_resultado', models.CharField(default=apps.ventas.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del análisis')),
                ('resultado', models.JSONField(verbose_name='Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analisis de predicciones',
                'verbose_name_plural': 'Analisis de predicciones',
                'db_table': 'resultado_analisis',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.CharField(default=apps.ventas.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('Servicio', 'Servicio')], max_length=125, verbose_name='Tipo')),
                ('costo_impresion', models.FloatField(default=0, verbose_name='Costo de Impresion')),
                ('costo_trabajo', models.FloatField(default=0, verbose_name='Costo de Trabajo')),
                ('total_venta', models.FloatField(default=0, editable=False, verbose_name='Total de la venta')),
                ('factura', models.BooleanField(default=False, verbose_name='Facturado')),
                ('impuesto_iva', models.IntegerField(default=13, editable=False, verbose_name='IMPUESTO IVA %')),
                ('impuesto_it', models.IntegerField(default=3, editable=False, verbose_name='IMPUESTO IT %')),
                ('analizada', models.BooleanField(default=False, verbose_name='Analizada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.cliente', verbose_name='Cliente')),
                ('insumos', models.ManyToManyField(related_name='detalles_ventas', to='compras.insumo', verbose_name='Insumos')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='empresa.inventario', verbose_name='Inventario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.CharField(default=apps.ventas.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('total', models.FloatField(default=0, editable=False, verbose_name='Total de la cotizacion')),
                ('impuesto', models.IntegerField(default=0, verbose_name='Impuesto (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='ventas.cliente', verbose_name='Cliente')),
                ('insumos', models.ManyToManyField(to='compras.insumo', verbose_name='Insumos')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizacion',
            },
        ),
    ]
