# Generated by Django 4.2.6 on 2023-11-02 16:37

import apps.empresa.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.CharField(default=apps.empresa.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=155, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.CharField(default=apps.empresa.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=155, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('latitud', models.CharField(blank=True, max_length=55, null=True, verbose_name='Latitud')),
                ('longitud', models.CharField(blank=True, max_length=55, null=True, verbose_name='Longitud')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.CharField(default=apps.empresa.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=155, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='empresa.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id_caracteristica', models.CharField(default=apps.empresa.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('detalle', models.TextField(blank=True, max_length=500, null=True, verbose_name='Detalle')),
                ('precio', models.FloatField(default=0, verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='empresa.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
                'db_table': 'caracteristica',
            },
        ),
    ]
