# Generated by Django 4.2.6 on 2023-11-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad en stock'),
        ),
    ]
