# Generated by Django 4.2.6 on 2023-11-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_inventario_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cantidad en stock'),
        ),
    ]
