# Generated by Django 4.2.6 on 2023-11-03 01:03

import apps.empresa.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_detallecompra_cantidad_and_more'),
        ('empresa', '0003_alter_inventario_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='cantidad',
        ),
        migrations.CreateModel(
            name='StockInsumo',
            fields=[
                ('id_stock_insumo', models.CharField(default=apps.empresa.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField(default=0, editable=False, verbose_name='Cantidad en stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.insumo', verbose_name='Insumo')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='empresa.inventario', verbose_name='Inventario')),
            ],
            options={
                'verbose_name': 'Stock de Insumo',
                'verbose_name_plural': 'Stocks de Insumos',
                'db_table': 'stock_insumo',
            },
        ),
    ]
